name: Access Environment-Specific Secret

description: 'A composite action to access environment-specific secrets.'

inputs:
  environment:
    description: "The environment to access secrets for (e.g., STAG_VN)"
    required: true
    default: "STAG_VN"

runs:
  using: 'composite'
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Access the HOST Secret
      env:
        HOST: ${{ secrets.HOST }}  # Assumes you have configured secrets for each environment
      shell: bash
      run: |
        echo "The HOST value is $HOST"
