name: 'Android Emulator Setup'
description: 'Sets up an Android SDK, creates an emulator, and starts it.'
runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    - name: Cache Android SDK
      id: cache-android-sdk
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/android-sdk
        key: android-sdk-${{ runner.os }}-${{ hashFiles('**/build.gradle', '**/pom.xml', '**/*.sdk-version') }}

    - name: Install Android SDK
      if: steps.cache-android-sdk.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
      shell: bash

    - name: Set up environment variables
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH" >> $GITHUB_ENV
        echo "$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator" >> $GITHUB_PATH
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
      shell: bash

    - name: Check Ubuntu environment variables
      run: |
        echo $ANDROID_HOME
        echo $PATH
      shell: bash

    - name: Accept Android SDK licenses
      run: |
        $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses | grep -v "Accept? (y/N):" | while read -r line; do echo "yes"; done
      shell: bash

    - name: Install SDK packages
      if: steps.cache-android-sdk.outputs.cache-hit != 'true'
      run: |
        $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "system-images;android-33;google_apis;x86_64" "emulator"
        if [ $? -eq 0 ]; then
            echo "Package install successfully"
          else
            echo "Package install failed" >&2
            exit 1
          fi
      shell: bash

    - name: Check install
      run: |
        find $HOME/android-sdk
      shell: bash

    - name: Create Android emulator
      run: |
        echo "no" | $HOME/android-sdk/cmdline-tools/tools/bin/avdmanager create avd -n emu -k "system-images;android-33;google_apis;x86_64" --device "pixel"
        if [ $? -eq 0 ]; then
            echo "AVD creation succeeded"
          else
            echo "AVD creation failed" >&2
            exit 1
          fi
      shell: bash

    - name: Start Android emulator
      run: |
        nohup $HOME/android-sdk/emulator/emulator -avd emu -no-snapshot-save -no-boot-anim -wipe-data -no-window -gpu off &
        $ANDROID_HOME/platform-tools/adb wait-for-device
      shell: bash

    - name: Check list devices
      run: |
        $ANDROID_HOME/platform-tools/adb devices
      shell: bash
