name: 'Android Emulator Setup'
description: 'Sets up an Android SDK, creates an emulator, and starts it.'
inputs:
  sdk-version:
    description: 'Android SDK version to install'
    required: true
    default: '33'
  java-version:
    description: 'Java version to use'
    required: true
    default: '22'
  avd-name:
    description: 'Name of the Android Virtual Device'
    required: true
    default: 'test'
runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk/cmdline-tools
        rm commandlinetools-linux-8512546_latest.zip
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
      shell: bash

    - name: Accept Android SDK licenses
      run: yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --licenses
      shell: bash

    - name: Create and start Android emulator
      run: |
        echo "no" | $HOME/android-sdk/cmdline-tools/tools/bin/avdmanager create avd -n ${{ inputs.avd-name }} -k "system-images;android-${{ inputs.sdk-version }};google_apis;x86_64" --device "pixel"
        nohup $HOME/android-sdk/emulator/emulator -avd ${{ inputs.avd-name }} -no-snapshot-save -no-boot-anim -wipe-data -no-window -gpu off &
        $HOME/android-sdk/platform-tools/adb wait-for-device
      shell: bash
